version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: empleados_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - employee-network

  webapp:
    build: .
    container_name: employee-management
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge

volumes:
  postgres_data: 